name: Profile Readme Development Stats

on:
  schedule:
    #updates at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme.md
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
		  		#SHOW_OS: "False"
		  		#SHOW_PROJECTS: "False"
